{% set name = "mathpad" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mathpad-{{ version }}.tar.gz
  sha256: e15e4df2b317e79d6777ebceaecbd59c5032a3ba54940fd846f7af2763122a38

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<3.10
  run:
    - numpy >=1.20,<2.0
    - python >=3.6,<3.10
    - scipy >=1.7.1,<2.0.0
    - sympy >=1.8,<2.0
    - typing-extensions >=4.0.0,<5.0.0

test:
  imports:
    - mathpad
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CallumJHays/mathpad
  summary: Simplified interface to Sympy for solving physics, engineering and maths problems
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CallumJHays
